### PR TITLE
Feature add security context

### PR DESCRIPTION
**Pull request by obeyler**
Give the opportunity to add a securityContext,
update readme.md to add array of parameter configuration
increase the chart number version

### CODE REVIEW

**Comment by georgifarashev** [comment]
Hi @obeyler. Sorry for the delayed response - I will try to check your change and give you feedback by the end of the day.

**Comment by georgifarashev** [comment]
Fixes: #44

**Comment by obeyler** [comment]
Thanks for the merge @georgifarashev @dzahariev could you tag a new release with it ?

**Comment by georgifarashev** [comment]
When a new release is created travis automatically uploads the latest version of the chart to it. So it will be available with the next release. There are no new code changes so we might postpone the release as the chart can be packaged manually (helm package command).

We might update our dependencies (and more specifically the service catalog version) so this will trigger a new release.

> Thanks for the merge @georgifarashev @dzahariev could you tag a new release with it ?
> The tag for the chart is 0.3.0 ;-)

**Comment by dzahariev** [comment]
@obeyler, we have a schedule to make releases for k8s proxy at Thursday on each even week (if there are changes of course). The next planed release is on 10th of January (we miss the week 52 because of holidays). Please clarify if this date suits for you, if not - we will release earlier.

**Comment by obeyler** [comment]
@dzahariev If you can release earlier or at least put tag a with version it will be great. 

We use tag to trigger a concourse pipeline who get src build it and pusch the helm chart into a Helm repository. So Without tag, no build no chart :-(  and we cannot use it into our CI

Lot of projects have divide into 2 projects the build of docker image of the app and the build of the chart.
see by example what is done on stable helm chart (https://github.com/helm/charts/tree/master/stable)
It is very usefull to do that as the evolution of these two parts are very differents.

**Comment by dzahariev** [comment]
@obeyler then, release is in preparation 👍

**Comment by obeyler** [comment]
Thanks ! :+1:

**Pull request merged**
